QSAId.register(:transfer, :prefix => 'T', :use_database_id => true)
QSAId.register(:transfer_proposal, :prefix => 'P', :use_database_id => true)
QSAId.register(:file_issue, :prefix => 'FI', :use_database_id => true)
QSAId.register(:file_issue_request, :prefix => 'FIR', :use_database_id => true)
QSAId.register(:search_request, :prefix => 'SR', :use_database_id => true)
QSAId.register(:agency_reading_room_request, :prefix => 'ARR', :use_database_id => true)
